# default values
all:
  
  appFlower:
    version: '1.0'
    loadingLogo: '/appFlowerPlugin/images/appFlowerAnimatedLogo.gif'
    logo: { file: '', url: 'http://www.appflower.com'}
    siteSecret: CHANGE_ME
  
  parser:
    panels:
      sidebar: [ ]
      footer: [ ]
    remove_fields: false
    denied: no/permission
    filepager_nohelp: 10000
    filepager_help: 8500
    filepager_all: 40000
    max_items: 10000
    default_layout: "[100]"
    export: { enabled: true, separator: ";" }
    host_type: "https://"
    skip_toolbar: true
     
  sfCombinePlugin:
    enabled:        false    # enabling the plugin will combine script and css files into a single file
    asset_version:  1       # key to the asset version (see below)
    js:
      minify:       true   # minification removes whitespaces and comments
      pack:         false   # packing reduces the filesize by using a JavaScript compression (warning: see below)
      online: [http://extjs.cachefly.net/builds/ext-cdn-771.js] #/sfExtjs2Plugin/extjs/adapter/ext/ext-base.js,/sfExtjs2Plugin/extjs/ext-all.js this files are skiped and added separatelly to response
      offline: [/appFlowerPlugin/extjs-3/adapter/ext/ext-base.js,/appFlowerPlugin/extjs-3/ext-all.js] # this files are skiped and added separatelly to response
    css:
      minify:       true    # only minification is available for css
      online: [http://extjs.cachefly.net/ext-2.2.1/resources/css/ext-all.css] # this files are skiped and added separatelly to response
      offline: [] # this files are skiped and added separatelly to response
    client_cache_max_age: 5  # enable the browser to keep a copy of the files for x days (false to disable)     
    
  cdn:
    active: false
    url: 'http://c0019995.cdn1.cloudfiles.rackspacecloud.com/'
