propel:
  _attributes:    { package: plugins.appFlowerPlugin.lib.model }

  sf_combine:
    _attributes:      { phpName: sfCombine }
    assets_key:       { type: varchar, size: 32, required: true, primaryKey: true }
    files:            { type: longvarchar, required: true }
    
  sf_combine_server:
    _attributes:      { phpName: sfCombineServer }
    id:               ~
    online:           boolean

  ############################################################################
  # - Portal State by radu --------------------------------------- #
  ############################################################################
  
  af_portal_state:
    _attributes: { phpName: afPortalState }
    id:
    id_xml: varchar(255)
    user_id: { type: integer }
    layout_type: varchar(255)
    content: LONGVARCHAR
    created_at:
    updated_at:
    
    
  ############################################################################
  # - WIDGET SETTING ------------------------------------------------------- #
  ############################################################################
  
  af_widget_setting:
    _attributes:               { phpName: afWidgetSetting }
    id:
    name:                      { type: varchar(255) }
    user:                      { type: integer }
    setting:                   { type: longvarchar }
    
  ############################################################################
  # - WIDGET Selector ------------------------------------------------------ #
  ############################################################################
  
  af_widget_selector:
    _attributes:               { phpName: afWidgetSelector }
    id:
    url:                       { type: varchar(128), index: true }
    params:                    { type: varchar(255) }
    category_id:               { type: integer, foreignTable: af_widget_category, foreignReference: id, onDelete: cascade }
    permission:                { type: varchar(255) }
    
  af_widget_category:
    _attributes:               { phpName: afWidgetCategory }
    id:
    module:                    { type: varchar(128), index: true }
    name:                      { type: varchar(255) }
    
  ############################################################################
  # - Parser Validator Cache ----------------------------------------------- #
  ############################################################################
  
  af_validator_cache:
    _attributes: { phpName: afValidatorCache }
    id:
    signature:    { type: varchar(40), index: true }
    path:         { type: varchar(255), index: true }
    created_at:
    updated_at:

  af_save_filter:
    _attributes: { phpName: afSaveFilter }
    id:
    name: { type: varchar(255) }
    user: { type: integer }
    path: { type: varchar(255) }
    title: { type: varchar(255) }
    filter: { type: longvarchar }

  af_notification:
    _attributes: { phpName: afNotification }
    id:
    title: { type: varchar(255)}
    message: { type: longvarchar }
    log: { type: longvarchar }
    type: { type: varchar(255)}
    duration: { type: integer}
    category: { type: integer }
    persistent: { type: integer }
    created_by: { type: integer }
    created_for: { type: integer }
    remote_ip: { type: varchar(255) }
    created_at:

  af_notified_for:
    _attributes: { phpName: afNotifiedFor }
    id: 
    user: { type: integer }
    notification_id: { type: integer, foreignTable: af_notification, foreignReference: id, onDelete: cascade }
    created_at:
    
  ############################################################################
  # - Widget Help Settings by radu ----------------------------------------- #
  ############################################################################
  
  af_widget_help_settings:
    _attributes: { phpName: afWidgetHelpSettings }
    id:
    user_id: { type: integer }
    widget_help_is_enabled:     { type: boolean, default: true }
    popup_help_is_enabled:      { type: boolean, default: true }
    help_type:                  { type: tinyint, default: 1 }
    created_at:
    updated_at: